apiVersion: apps/v1
kind: Deployment
metadata:
  name: init-gridu-deployment-4
  labels:
    app: gridu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gridu-4
  template:
    metadata:
      labels:
        app: gridu-4
    spec:
      containers:
      - name: gridu
        image: quay.io/myafk/interactive:stable
        command: ["interactive", "config", "-t=fourth"]
        volumeMounts:
          - name: config
            mountPath: /mnt
      volumes:
        - name: config
          secret:
            secretName: gridu-secret
